local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.AWS_ACCESS_KEY_ID %>
  secret_access_key: <%= Rails.application.credentials.AWS_SECRET_ACCESS_KEY %>
  bucket: <%= Rails.application.credentials.AWS_BUCKET %>
  region: <%= Rails.application.credentials.AWS_REGION %> # e.g. 'us-east-1'

# AWS_ACCESS_KEY_ID: 'AKIAZJCUHMSXTLROX63T'
# AWS_SECRET_ACCESS_KEY: 'BzxnxbsEjmgW43ql6Imp/eh+4tmBD7VMF4LhKxSI'
# AWS_BUCKET: 'nxt11'
# AWS_REGION: "us-east-1"